### ISSUE TITLE
Melting Snowman Implementation 100%

### ISSUE THREAD

**Issue by ChavaRaitzik** [ChavaRaitzik/Melting-Snowman#3]

**Comment by ghost** [comment]
Excellent work! Really nice UI. QA is good. Some comments.
- I don't know if `CrypticWizard.RandomWordGenerator` has a definition option but if it does, I would like to have a hint button.

See more comments in file, fix and resubmit.

**Comment by ChavaRaitzik** [comment]
Thanks. Although a hint button would enhance the game, as far as I know the random word generator does not have definitions, and I did not include a hint option in my spec.

**Comment by ChavaRaitzik** [comment]
I did not include a hint option in my spec.

**Comment by ChavaRaitzik** [comment]
Corrections made.

**Comment by ghost** [comment]
Excellent! 100% See some refactoring comments, no need to resubmit.
