### ISSUE TITLE
UI Improvements 100%

### ISSUE THREAD

**Issue by ghost** [ChavaRaitzik/Melting-Snowman#4]
Once the game is playing you shouldn't be able to click start again. Maybe add a button like I give up.

**Comment by ChavaRaitzik** [comment]
Thank you. I added the option to give up.

**Comment by shmielcpu** [comment]
You should disable the buttons based on the game status. If it's playing you should only be able to click give up and if it's not playing you should only be able to click start.

**Comment by ghost** [comment]
I just saw that you allow start button to be clicked even only till user starts playing.
